### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by wahidisna** [cubiclesoft/portable-apache-maria-db-php-for-windows#10]
I use windows 10 64 bit

When I execute `install.bat`, I get this error:
```

Fatal error:  Download failed.
Error retrieving URL.  Unable to retrieve content.  Unable to establish a connection to 'ssl://www.apachelounge.com:443'.
```

The protocol is not `https`, but `ssl`
How to fix this?
Thank you

**Comment by cubiclesoft** [comment]
The protocol and connection string are correct.  The error is being emitted from the [Ultimate Web Scraper Toolkit](https://github.com/cubiclesoft/ultimate-web-scraper).  Enabling debugging in a request to the server in a test script shows:

```
PHP Warning:  stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed in support\support\http.php on line 1861

Warning: stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed in support\support\http.php on line 1861
PHP Warning:  stream_socket_client(): Failed to enable crypto in support\support\http.php on line 1861

Warning: stream_socket_client(): Failed to enable crypto in support\support\http.php on line 1861
PHP Warning:  stream_socket_client(): unable to connect to ssl://www.apachelounge.com:443 (Unknown error) in support\support\http.php on line 1861

Warning: stream_socket_client(): unable to connect to ssl://www.apachelounge.com:443 (Unknown error) in support\support\http.php on line 1861
```

Running the same code against a newer version of PHP retrieves content from the server as expected.  So basically the version of PHP that is bundled with this installer is now so outdated that it can't communicate with the remote host that it needs to communicate with.  I'd wager it has to do with SNI support or a general lack thereof.  Two options exist:  Disable SSL/TLS verification (a very bad idea) or upgrade the bundled PHP to something more recent (a not great idea because of how modern PHP works).  I've updated this project using the [Portable Apps Proxy](https://github.com/cubiclesoft/portable-apps-mirror-proxy) minimalistic prepackaged PHP that's about a 6MB increase in project size.  The updated version of PHP seems to work.

It also looks like MariaDB downloads are broken too.  Just fixed that as well.

Try downloading this project again.  Everything should be working as expected now.
