### ISSUE TITLE
port configuration 

### ISSUE THREAD

**Issue by anasfanani** [cubiclesoft/portable-apache-maria-db-php-for-windows#6]
where i can set port configuration if port 80 already used

**Comment by cubiclesoft** [comment]
You'll have to modify `apache/conf/httpd.conf`.  Locate the `Listen 80` line.  Change it to whatever port you want.

I do assume a clean system for this project.  If there's another server running on port 80, then I recommend disabling that process first.  It's probably Apache or IIS.

**Comment by cubiclesoft** [comment]
Another option I just thought of is to use an alternate IP address with Listen like `Listen 127.0.1.1:80` and then connect to that specific IP in your browser.  As long as the other service on port 80 is only attached to 127.0.0.1, it should work.  127.*.*.* is all localhost/loopback, so you have almost 16.7 million IPs to choose from.

It might work anyway since Windows tends to allow layered overlapping services even if 0.0.0.0:80 was used by another service.  That is, 0.0.0.0 binds all interfaces and says route port 80 to the target service but Windows tends to allow other services to start on specific IPs even in that scenario but specifically won't allow 127.0.0.1:80.  At least, that's been my experience on the rare occasion when I've run conflicting port binds.
