### ISSUE TITLE
Add xdebug!

### ISSUE THREAD

**Issue by beppe9000** [cubiclesoft/portable-apache-maria-db-php-for-windows#7]
A good idea would be a script to toggle xdebug

**Comment by cubiclesoft** [comment]
Every time I've ever used PECL Xdebug, it has never worked properly for whatever I want it for at the time...usually memory leak tracing or performance tracking.  And the tools to read Xdebug dumps on most platforms, especially Windows, are rather lacking.  `var_dump()` is my go-to debugging tool.  That's not to say there isn't merit behind Xdebug - I'm just saying I rarely use/need it and I write plenty of complex software projects in PHP.

Toggling probably requires stopping Apache, modifying the INI, and then starting Apache again.  A fairly short PHP script could handle modifying its own INI file to perform such a toggle.

On a broader note:  PECL extensions are quite picky about the versions of PHP they work with.  Getting them working on Windows is difficult mostly because of how the Windows loader works (e.g. DLLs can't relative-reference loading other DLLs via DLL imports).  Busting out [Microsoft SysInternals Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) and [Dependencies](https://github.com/lucasg/Dependencies) to figure out what file fails to load and why and then figure out how to fix it is not particularly fun.  There are a lot of interesting PECL extensions but PECL is barely supported on Linux and even less so on Windows.  If I add Xdebug, other people will want other popular PECL extensions like ImageMagick/GraphicsMagick, Swoole, libev, protobuf, etc. to also be included.  Each one would add weight and ultimately become a code maintenance nightmare.  I prefer a vanilla installation and then let people opt to customize from there for their environment.  Not everyone likes Xdebug.

I've added some documentation on setting up PECL extensions.  It should give users the tools they need to install extensions on their own along with sufficient guidance on solving various problems that crop up.

**Comment by beppe9000** [comment]
that's a good point indeed. better keep this simple. i think i will use uwamp for when xdebug is needed since it is in there by default
